# Generated by Django 4.2.5 on 2023-09-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('views', models.IntegerField(blank=True, null=True, verbose_name='Просмотры поста')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выхода')),
                ('stats_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата статистики')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
