# Generated by Django 4.2.5 on 2023-09-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена до снятия статистики'),
        ),
    ]
